#[path = "filesystem_identity/credential_globs_and_roots_follow_the_lexical_owner.rs"]
pub mod credential_globs_and_roots_follow_the_lexical_owner;
#[path = "filesystem_identity/detector_success_and_failure.rs"]
pub mod detector_success_and_failure;
#[path = "support/differential.rs"]
pub mod differential;
#[path = "filesystem_identity/disk_readlink_errno_partitions_match_go.rs"]
pub mod disk_readlink_errno_partitions_match_go;
#[path = "filesystem_identity/escaped_home_keeps_broad_root_protection.rs"]
pub mod escaped_home_keeps_broad_root_protection;
#[path = "filesystem_identity/explicit_missing_public_ssh_files_preserve_go_roles.rs"]
pub mod explicit_missing_public_ssh_files_preserve_go_roles;
#[path = "filesystem_identity/git_owns_quoted_pathspec_globs.rs"]
pub mod git_owns_quoted_pathspec_globs;
#[path = "filesystem_identity/listing_option_values_and_children.rs"]
pub mod listing_option_values_and_children;
#[path = "filesystem_identity/ordinary_directory_globs_do_not_intersect_wildcard_only_credential_tails.rs"]
pub mod ordinary_directory_globs_do_not_intersect_wildcard_only_credential_tails;
#[path = "filesystem_identity/physical_links_keep_order_and_eight_hop_bound.rs"]
pub mod physical_links_keep_order_and_eight_hop_bound;
#[path = "support/batch6.rs"]
pub mod program_contract;
#[path = "filesystem_identity/public_ssh_backup_suffixes_keep_lexical_identity.rs"]
pub mod public_ssh_backup_suffixes_keep_lexical_identity;
#[path = "filesystem_identity/runtime_unknown_prefix_preserves_appdata_tail_protection.rs"]
pub mod runtime_unknown_prefix_preserves_appdata_tail_protection;
#[path = "filesystem_identity/shell.rs"]
pub mod shell;
#[path = "filesystem_identity/ssh_public_file_type_and_probe_fault.rs"]
pub mod ssh_public_file_type_and_probe_fault;
pub(crate) mod support;
