#[path = "support/differential.rs"]
pub mod differential;
#[path = "lifecycle/entry_group_cleanup.rs"]
pub mod entry_group_cleanup;
#[path = "lifecycle/nesting_frontier_completes_on_default_test_stack.rs"]
pub mod nesting_frontier_completes_on_default_test_stack;
#[path = "support/batch6.rs"]
pub mod program_contract;
#[path = "lifecycle/shell_entry_hands_stdin_to_checker.rs"]
pub mod shell_entry_hands_stdin_to_checker;
#[path = "lifecycle/stalled_check_reports_the_checker_deadline_and_reaps.rs"]
pub mod stalled_check_reports_the_checker_deadline_and_reaps;
#[path = "lifecycle/supervisor_deadline_kills_and_reaps_the_recorded_child.rs"]
pub mod supervisor_deadline_kills_and_reaps_the_recorded_child;
pub(crate) mod support;
