#[path = "shell_state/accumulation_consumers_preserve_fields.rs"]
pub mod accumulation_consumers_preserve_fields;
#[path = "shell_state/and_chains_preserve_success_and_failure_directories.rs"]
pub mod and_chains_preserve_success_and_failure_directories;
#[path = "shell_state/and_success_continuation_defines_public_helpers.rs"]
pub mod and_success_continuation_defines_public_helpers;
#[path = "shell_state/and_success_excludes_failed_cwd.rs"]
pub mod and_success_excludes_failed_cwd;
#[path = "shell_state/benign_nested_loops_do_not_exhaust_inspection.rs"]
pub mod benign_nested_loops_do_not_exhaust_inspection;
#[path = "shell_state/bound_arithmetic_sinks_observe_subscript_code.rs"]
pub mod bound_arithmetic_sinks_observe_subscript_code;
#[path = "shell_state/conditional_literal_accumulation_preserves_targets.rs"]
pub mod conditional_literal_accumulation_preserves_targets;
#[path = "support/differential.rs"]
pub mod differential;
#[path = "shell_state/doubled_values_refuse_past_the_expansion_bounds.rs"]
pub mod doubled_values_refuse_past_the_expansion_bounds;
#[path = "shell_state/eval_runtime_output_is_unresolved_code.rs"]
pub mod eval_runtime_output_is_unresolved_code;
#[path = "shell_state/executable_flow.rs"]
pub mod executable_flow;
#[path = "shell_state/function_argv_preserves_fields_and_scope.rs"]
pub mod function_argv_preserves_fields_and_scope;
#[path = "shell_state/indexed_arrays_preserve_elements.rs"]
pub mod indexed_arrays_preserve_elements;
#[path = "shell_state/indexed_parameter_expansion_evaluates_binding.rs"]
pub mod indexed_parameter_expansion_evaluates_binding;
#[path = "shell_state/literal_for_lists_execute_each_value_exactly.rs"]
pub mod literal_for_lists_execute_each_value_exactly;
#[path = "shell_state/loop_cwd_widening_preserves_protected_candidates.rs"]
pub mod loop_cwd_widening_preserves_protected_candidates;
#[path = "shell_state/matrix_candidates_keep_all_shell_read_operands.rs"]
pub mod matrix_candidates_keep_all_shell_read_operands;
#[path = "shell_state/nested_functions_follow_dynamic_local_scope.rs"]
pub mod nested_functions_follow_dynamic_local_scope;
#[path = "shell_state/ordinary_small_command_cost.rs"]
pub mod ordinary_small_command_cost;
#[path = "shell_state/persistent_binding_eligibility.rs"]
pub mod persistent_binding_eligibility;
#[path = "shell_state/pipeline_read_models_known_values_and_refuses_unmodelled_armed_reads.rs"]
pub mod pipeline_read_models_known_values_and_refuses_unmodelled_armed_reads;
#[path = "shell_state/pipeline_read_receives_protected_and_armed_producer_values.rs"]
pub mod pipeline_read_receives_protected_and_armed_producer_values;
#[path = "shell_state/prefix_assignments_use_prior_prefix_values.rs"]
pub mod prefix_assignments_use_prior_prefix_values;
#[path = "shell_state/process_streams_feed_item_and_stdin_consumers.rs"]
pub mod process_streams_feed_item_and_stdin_consumers;
#[path = "support/batch6.rs"]
pub mod program_contract;
#[path = "shell_state/quoted_tilde_runtime_prefix_stays_relative.rs"]
pub mod quoted_tilde_runtime_prefix_stays_relative;
#[path = "shell_state/read_names_replace_armed_bindings.rs"]
pub mod read_names_replace_armed_bindings;
#[path = "shell_state/read_writes_every_destination.rs"]
pub mod read_writes_every_destination;
#[path = "shell_state/reassignment_replaces_copied_armed_value.rs"]
pub mod reassignment_replaces_copied_armed_value;
#[path = "shell_state/repeated_loop_references_share_one_binding_candidate.rs"]
pub mod repeated_loop_references_share_one_binding_candidate;
#[path = "shell_state/shell_glob_loop_items_keep_protected_intersection_at_sinks.rs"]
pub mod shell_glob_loop_items_keep_protected_intersection_at_sinks;
#[path = "shell_state/shell_list_length_is_not_syntactic_nesting.rs"]
pub mod shell_list_length_is_not_syntactic_nesting;
#[path = "shell_state/shell_observation_reuse.rs"]
pub mod shell_observation_reuse;
#[path = "shell_state/substitution_bindings_remain_single_unknown_words.rs"]
pub mod substitution_bindings_remain_single_unknown_words;
pub(crate) mod support;
#[path = "shell_state/unknown_producer_values_are_not_reparsed_as_lexical_shell_code.rs"]
pub mod unknown_producer_values_are_not_reparsed_as_lexical_shell_code;
#[path = "shell_state/unknown_read_aggregation_converges_without_literal_path_loss.rs"]
pub mod unknown_read_aggregation_converges_without_literal_path_loss;
