#[path = "shell_syntax/ansi_c_words.rs"]
pub mod ansi_c_words;
#[path = "shell_syntax/ansi_prefix_preserves_brace_reach.rs"]
pub mod ansi_prefix_preserves_brace_reach;
#[path = "shell_syntax/array_closer_divergence_blocks_both_host_readings.rs"]
pub mod array_closer_divergence_blocks_both_host_readings;
#[path = "shell_syntax/detector_success_and_failure.rs"]
pub mod detector_success_and_failure;
#[path = "support/differential.rs"]
pub mod differential;
#[path = "shell_syntax/double_quotes_keep_inner_apostrophes_literal.rs"]
pub mod double_quotes_keep_inner_apostrophes_literal;
#[path = "shell_syntax/git_owns_quoted_pathspec_globs.rs"]
pub mod git_owns_quoted_pathspec_globs;
#[path = "shell_syntax/heredoc_parentheses_remain_data.rs"]
pub mod heredoc_parentheses_remain_data;
#[path = "shell_syntax/mixed_quote_fields_do_not_turn_filter_data_into_root_operands.rs"]
pub mod mixed_quote_fields_do_not_turn_filter_data_into_root_operands;
#[path = "shell_syntax/nested_parameter_flags_refuse_without_checker_faults.rs"]
pub mod nested_parameter_flags_refuse_without_checker_faults;
#[path = "shell_syntax/parser_corpus_preserves_spans_and_frozen_agreement.rs"]
pub mod parser_corpus_preserves_spans_and_frozen_agreement;
#[path = "shell_syntax/prefix_assignments_use_prior_prefix_values.rs"]
pub mod prefix_assignments_use_prior_prefix_values;
#[path = "support/batch6.rs"]
pub mod program_contract;
#[path = "shell_syntax/quoted_substitution_heredoc_bodies_are_inert_word_data.rs"]
pub mod quoted_substitution_heredoc_bodies_are_inert_word_data;
#[path = "shell_syntax/shell.rs"]
pub mod shell;
#[path = "shell_syntax/shell_word_blanks_keep_benign_permits.rs"]
pub mod shell_word_blanks_keep_benign_permits;
#[path = "shell_syntax/subshell_case_patterns_are_not_group_closers.rs"]
pub mod subshell_case_patterns_are_not_group_closers;
pub(crate) mod support;
#[path = "shell_syntax/visible_shell_matches_and_literal_search_roots_skip_hidden_credentials.rs"]
pub mod visible_shell_matches_and_literal_search_roots_skip_hidden_credentials;
