#[path = "targets/client_specs_preserve_file_roles.rs"]
pub mod client_specs_preserve_file_roles;
#[path = "targets/copy_destination_is_written_without_reading_its_contents.rs"]
pub mod copy_destination_is_written_without_reading_its_contents;
#[path = "targets/credential_globs_and_roots_follow_the_lexical_owner.rs"]
pub mod credential_globs_and_roots_follow_the_lexical_owner;
#[path = "targets/ctags_atfile_values_read_and_global_values_remain_names.rs"]
pub mod ctags_atfile_values_read_and_global_values_remain_names;
#[path = "targets/ctags_owns_its_option_file_references.rs"]
pub mod ctags_owns_its_option_file_references;
#[path = "targets/curl_urls_after_double_dash_keep_their_read_role.rs"]
pub mod curl_urls_after_double_dash_keep_their_read_role;
#[path = "support/differential.rs"]
pub mod differential;
#[path = "targets/du_option_files_have_list_role.rs"]
pub mod du_option_files_have_list_role;
#[path = "targets/fd_option_values_and_child_options_do_not_select_hidden_listing.rs"]
pub mod fd_option_values_and_child_options_do_not_select_hidden_listing;
#[path = "targets/filters_are_data_and_later_operands_remain_readable.rs"]
pub mod filters_are_data_and_later_operands_remain_readable;
#[path = "targets/find_leading_options_preserve_roots.rs"]
pub mod find_leading_options_preserve_roots;
#[path = "targets/git_config_values_keep_fallback_read_role.rs"]
pub mod git_config_values_keep_fallback_read_role;
#[path = "targets/git_environment_reaches_wrappers_and_child_shells.rs"]
pub mod git_environment_reaches_wrappers_and_child_shells;
#[path = "targets/git_owns_quoted_pathspec_globs.rs"]
pub mod git_owns_quoted_pathspec_globs;
#[path = "targets/global_option_values_never_consume_an_option.rs"]
pub mod global_option_values_never_consume_an_option;
#[path = "targets/global_pattern_names_follow_the_generic_owner.rs"]
pub mod global_pattern_names_follow_the_generic_owner;
#[path = "targets/grep_equals_values_and_install_destination_keep_owner_roles.rs"]
pub mod grep_equals_values_and_install_destination_keep_owner_roles;
#[path = "targets/listing_option_values_and_children.rs"]
pub mod listing_option_values_and_children;
#[path = "targets/literal_for_lists_execute_each_value_exactly.rs"]
pub mod literal_for_lists_execute_each_value_exactly;
#[path = "targets/metadata_operands_do_not_read_credential_contents.rs"]
pub mod metadata_operands_do_not_read_credential_contents;
#[path = "targets/native_legacy_client_roles_match_go_without_losing_protection.rs"]
pub mod native_legacy_client_roles_match_go_without_losing_protection;
#[path = "targets/opaque_operands_refuse_broad_roots.rs"]
pub mod opaque_operands_refuse_broad_roots;
#[path = "targets/optional_inplace_suffix_preserves_inline_code.rs"]
pub mod optional_inplace_suffix_preserves_inline_code;
#[path = "targets/precommand_wrappers_reach_the_actual_program.rs"]
pub mod precommand_wrappers_reach_the_actual_program;
#[path = "targets/process_names_and_perl_argv_preserve_roles.rs"]
pub mod process_names_and_perl_argv_preserve_roles;
#[path = "support/batch6.rs"]
pub mod program_contract;
#[path = "targets/quoted_pattern_regions_keep_local_expansion.rs"]
pub mod quoted_pattern_regions_keep_local_expansion;
#[path = "targets/recognised_wrappers_preserve_effective_git_environment.rs"]
pub mod recognised_wrappers_preserve_effective_git_environment;
#[path = "targets/shell.rs"]
pub mod shell;
pub(crate) mod support;
#[path = "targets/tar_short_values_keep_their_read_or_write_roles.rs"]
pub mod tar_short_values_keep_their_read_or_write_roles;
#[path = "targets/tracked_cwd_entry_follows_go_named_target_rule.rs"]
pub mod tracked_cwd_entry_follows_go_named_target_rule;
