#[path = "wire/detector_success_and_failure.rs"]
pub mod detector_success_and_failure;
#[path = "support/differential.rs"]
pub mod differential;
#[path = "wire/every_legacy_row_is_accounted_for.rs"]
pub mod every_legacy_row_is_accounted_for;
#[path = "wire/expired_evaluation_deadline_blocks_every_consumer.rs"]
pub mod expired_evaluation_deadline_blocks_every_consumer;
#[path = "wire/failures_block_from_consumer_wire.rs"]
pub mod failures_block_from_consumer_wire;
#[path = "wire/invalid_json_keeps_failure_without_echoing_input.rs"]
pub mod invalid_json_keeps_failure_without_echoing_input;
#[path = "wire/jsonl_dev_contract_and_parser_boundary.rs"]
pub mod jsonl_dev_contract_and_parser_boundary;
#[path = "support/batch6.rs"]
pub mod program_contract;
#[path = "wire/shell.rs"]
pub mod shell;
pub(crate) mod support;
#[path = "wire/tool_names_follow_go_case_folding.rs"]
pub mod tool_names_follow_go_case_folding;
#[path = "wire/tool_names_follow_go_simple_rune_mapping.rs"]
pub mod tool_names_follow_go_simple_rune_mapping;
#[path = "wire/version_reports_the_release_owner.rs"]
pub mod version_reports_the_release_owner;
